### PR TITLE
Added the Guide

### PR DESCRIPTION
**Pull request by mraza007**
I have added the contribution guide

### CODE REVIEW

**Comment by mraza007** [comment]
I have fixed most of it not sure how to fix the merge conflict

**Comment by mraza007** [comment]
I Still cannot merge it

**Comment by jslay88** [comment]
You cannot merge it because you still have not made the requests changes.

**Comment by mraza007** [comment]
Sure I'll fix it

**Comment by mraza007** [comment]
I have removed old assets and created a new branch

**Comment by DulalSandip** [comment]
the code doenst work well as it is not downloading any videos

**Comment by mraza007** [comment]
It’s been a while this project is not being maintained

**Pull request closed without merging**
